Repository fitbenchmarking/fitbenchmarking, pull requests merged in 2019-11, with the labels that each got.

#281 216 add dfo gn
  docs/source/contributors/extending_fitbenchmarking.rst
  docs/source/users/options.rst
  fitbenchmarking/fitbenchmark_one_problem.py
  fitbenchmarking/fitbenchmarking_default_options.json
  fitbenchmarking/fitting/controllers/dfogn_controller.py
  fitbenchmarking/fitting/tests/test_controllers.py
  setup.py
Labels: Fitting software

#261 Moving data sorting from plotting to data input
  fitbenchmarking/fitbenchmark_one_problem.py
  fitbenchmarking/fitting/controllers/base_controller.py
  fitbenchmarking/fitting/plotting/plot_helper.py
  fitbenchmarking/fitting/plotting/plots.py
  fitbenchmarking/parsing/base_fitting_problem.py
  fitbenchmarking/parsing/parse.py
Labels: Maintenance

#284 215 Adding RALfit
  .travis.yml
  build_ralfit.sh
  docs/source/users/getting_started.rst
  docs/source/users/options.rst
  fitbenchmarking/fitbenchmark_one_problem.py
  fitbenchmarking/fitbenchmarking_default_options.json
  fitbenchmarking/fitting/controllers/ralfit_controller.py
  fitbenchmarking/fitting/tests/test_controllers.py
Labels: Enhancement

#289 remove travis-ci settings env vars
  .travis.yml
Labels: Maintenance

#285 257 Adding averaging time using timeit
  docs/source/users/options.rst
  example_scripts/example_runScripts_expert.py
  fitbenchmarking/fitbenchmark_one_problem.py
  fitbenchmarking/fitbenchmarking_default_options.json
  fitbenchmarking/fitting_benchmarking.py
Labels: Enhancement

#298 295 notable combinations table
  docs/source/users/index.rst
  docs/source/users/notes.rst
  docs/source/users/options.rst
Labels: Documentation

#304 300 table generation
  README.md
  docs/images/example_table.png
  docs/source/users/options.rst
  example_scripts/example_runScripts.py
  example_scripts/example_runScripts_expert.py
  fitbenchmarking/fitbenchmarking_default_options.json
  fitbenchmarking/fitting/controllers/sasview_controller.py
  fitbenchmarking/fitting/controllers/scipy_controller.py
  fitbenchmarking/resproc/color_definitions.txt
  fitbenchmarking/resproc/numpy_restables.py
  fitbenchmarking/resproc/rst_table.py
  fitbenchmarking/resproc/tests/test_numpy_restables.py
  fitbenchmarking/resproc/tests/test_rst_table.py
  fitbenchmarking/results_output.py
  fitbenchmarking/utils/tests/test_misc.py
  setup.py
Labels: Enhancement

#314 Issue #313: Add path on externals install and echo message for user t…
  build/install/mantid.sh
Labels: Bug, Fitting software, Priority - high

#329 Issue #323: Add default value for x in eval_f
  fitbenchmarking/fitting/controllers/dfogn_controller.py
  fitbenchmarking/fitting/controllers/minuit_controller.py
  fitbenchmarking/fitting/controllers/ralfit_controller.py
  fitbenchmarking/fitting/controllers/scipy_controller.py
  fitbenchmarking/parsing/fitting_problem.py
  fitbenchmarking/parsing/tests/test_fitting_problem.py
Labels: Maintenance

#327 Issue #322: Refactor functions var in fitting_problem
  fitbenchmarking/fitbenchmark_one_problem.py
  fitbenchmarking/fitting/controllers/base_controller.py
  fitbenchmarking/fitting/controllers/dfogn_controller.py
  fitbenchmarking/fitting/controllers/mantid_controller.py
  fitbenchmarking/fitting/controllers/minuit_controller.py
  fitbenchmarking/fitting/controllers/ralfit_controller.py
  fitbenchmarking/fitting/controllers/sasview_controller.py
  fitbenchmarking/fitting/controllers/scipy_controller.py
  fitbenchmarking/fitting/tests/test_controllers.py
  fitbenchmarking/parsing/fitbenchmark_parser.py
  fitbenchmarking/parsing/fitting_problem.py
  fitbenchmarking/parsing/nist_data_functions.py
  fitbenchmarking/parsing/nist_parser.py
  fitbenchmarking/parsing/sasview_parser.py
  fitbenchmarking/parsing/tests/expected/basic.json
  fitbenchmarking/parsing/tests/expected/start_end_x.json
  fitbenchmarking/parsing/tests/test_fitting_problem.py
  fitbenchmarking/parsing/tests/test_parsers.py
Labels: Maintenance, Refactor
