Repository fitbenchmarking/fitbenchmarking, pull requests merged in 2020-06, with the labels that each got.

#569 Combining benchmarking functions in core
  fitbenchmarking/cli/main.py
  fitbenchmarking/core/fitbenchmark_one_problem.py
  fitbenchmarking/core/fitting_benchmarking.py
  fitbenchmarking/core/tests/test_fitbenchmark_one_problem.py
  fitbenchmarking/utils/exceptions.py
Labels: Enhancement, Priority - high, backport-candidate

#573 Refactor and document Controller.flag
  docs/source/extending/controllers.rst
  fitbenchmarking/controllers/base_controller.py
  fitbenchmarking/controllers/tests/test_controllers.py
Labels: Documentation, Refactor

#566 Default maxdepth in toctree
  docs/source/concept/how/index.rst
  docs/source/contributors/index.rst
  docs/source/extending/outputs/index.rst
  docs/source/index.rst
  docs/source/users/index.rst
  docs/source/users/install_instructions/externals/index.rst
  docs/source/users/install_instructions/index.rst
  docs/source/users/output/index.rst
  docs/source/users/problem_definition_files/index.rst
Labels: backport-candidate

#575 Enable CT for release branch
  .travis.yml
Labels: Enhancement, In progress, backport-candidate
