Repository fitbenchmarking/fitbenchmarking, pull requests merged in 2020-10, with the labels that each got.

#603 Azure test incorrect report
  azure-pipelines.yml
  fitbenchmarking/core/tests/test_fitting_benchmarking_benchmark.py
  fitbenchmarking/core/tests/test_fitting_benchmarking_benchmark_problems.py
  fitbenchmarking/core/tests/test_fitting_benchmarking_minimizers.py
  fitbenchmarking/core/tests/test_fitting_benchmarking_software.py
  fitbenchmarking/core/tests/test_fitting_benchmarking_starting_values.py
  fitbenchmarking/core/tests/test_results_output.py
  fitbenchmarking/systests/linux_expected_results/all_parsers.txt
  fitbenchmarking/systests/linux_expected_results/default_parsers.txt
  fitbenchmarking/systests/linux_expected_results/multifit.txt
  fitbenchmarking/systests/test_regression.py
  fitbenchmarking/systests/win32_expected_results/default_parsers.txt
  fitbenchmarking/utils/options.py
  fitbenchmarking/utils/tests/test_options_generic.py
Labels: Bug, Testing

#669 Fixing Azure tests
  azure-pipelines.yml
  fitbenchmarking/results_processing/support_page.py
  fitbenchmarking/results_processing/tests/test_support_page.py
Labels: Bug, Testing, backport-candidate

#654 Cost function class
  docs/source/extending/controllers.rst
  docs/source/extending/cost_function.rst
  docs/source/extending/index.rst
  docs/source/extending/jacobian_extend.rst
  docs/source/users/options/fitting_option.rst
  fitbenchmarking/controllers/base_controller.py
  fitbenchmarking/controllers/bumps_controller.py
  fitbenchmarking/controllers/dfo_controller.py
  fitbenchmarking/controllers/gsl_controller.py
  fitbenchmarking/controllers/mantid_controller.py
  fitbenchmarking/controllers/minuit_controller.py
  fitbenchmarking/controllers/ralfit_controller.py
  fitbenchmarking/controllers/scipy_controller.py
  fitbenchmarking/controllers/scipy_ls_controller.py
  fitbenchmarking/controllers/tests/test_controllers.py
  fitbenchmarking/core/fitting_benchmarking.py
  fitbenchmarking/core/tests/test_fitting_benchmarking_benchmark.py
  fitbenchmarking/core/tests/test_fitting_benchmarking_benchmark_problems.py
  fitbenchmarking/core/tests/test_fitting_benchmarking_jacobians.py
  fitbenchmarking/core/tests/test_fitting_benchmarking_minimizers.py
  fitbenchmarking/core/tests/test_fitting_benchmarking_software.py
  fitbenchmarking/core/tests/test_fitting_benchmarking_starting_values.py
  fitbenchmarking/core/tests/test_results_output.py
  fitbenchmarking/cost_func/__init__.py
  fitbenchmarking/cost_func/base_cost_func.py
  fitbenchmarking/cost_func/cost_func_factory.py
  fitbenchmarking/cost_func/nlls_cost_func.py
  fitbenchmarking/cost_func/tests/test_cost_func.py
  fitbenchmarking/jacobian/analytic_jacobian.py
  fitbenchmarking/jacobian/base_jacobian.py
  fitbenchmarking/jacobian/scipy_jacobian.py
  fitbenchmarking/jacobian/tests/test_jacobian.py
  fitbenchmarking/parsing/fitting_problem.py
  fitbenchmarking/parsing/tests/test_fitting_problem.py
  fitbenchmarking/parsing/tests/test_parsers.py
  fitbenchmarking/results_processing/local_min_table.py
  fitbenchmarking/results_processing/plots.py
  fitbenchmarking/results_processing/tests/test_performance_profiler.py
  fitbenchmarking/results_processing/tests/test_plots.py
  fitbenchmarking/results_processing/tests/test_support_page.py
  fitbenchmarking/results_processing/tests/test_tables.py
  fitbenchmarking/utils/exceptions.py
  fitbenchmarking/utils/fitbm_result.py
  fitbenchmarking/utils/options.py
  fitbenchmarking/utils/tests/test_fitbm_result.py
  fitbenchmarking/utils/tests/test_options_fitting.py
  travis/unit_tests.sh
  travis/unit_tests_default.sh
Labels: Enhancement, Refactor
