Repository fitbenchmarking/fitbenchmarking, pull requests merged in 2020-01, with the labels that each got.

#370 Issue #345: Add META file for each dataset and use first line as label
  examples/benchmark_problems/CUTEst/META.txt
  examples/benchmark_problems/Muon/META.txt
  examples/benchmark_problems/NIST/average_difficulty/META.txt
  examples/benchmark_problems/NIST/high_difficulty/META.txt
  examples/benchmark_problems/NIST/low_difficulty/META.txt
  examples/benchmark_problems/Neutron/META.txt
  examples/benchmark_problems/SAS_modelling/1D/META.txt
  examples/benchmark_problems/simple_tests/META.txt
  fitbenchmarking/cli/main.py
  fitbenchmarking/utils/misc.py
Labels: Enhancement

#369 Adds top level index page
  fitbenchmarking/HTML_templates/index_page.html
  fitbenchmarking/HTML_templates/results_template.html
  fitbenchmarking/HTML_templates/style_sheet.css
  fitbenchmarking/resproc/visual_pages.py
  fitbenchmarking/results_output.py
Labels: Enhancement

#380 Issue #347: Restructure directories
  .travis.yml
  fitbenchmarking/cli/main.py
  fitbenchmarking/controllers/__init__.py
  fitbenchmarking/controllers/base_controller.py
  fitbenchmarking/controllers/controller_factory.py
  fitbenchmarking/controllers/dfogn_controller.py
  fitbenchmarking/controllers/gsl_controller.py
  fitbenchmarking/controllers/mantid_controller.py
  fitbenchmarking/controllers/minuit_controller.py
  fitbenchmarking/controllers/ralfit_controller.py
  fitbenchmarking/controllers/sasview_controller.py
  fitbenchmarking/controllers/scipy_controller.py
  fitbenchmarking/controllers/tests/__init__.py
  fitbenchmarking/controllers/tests/test_controllers.py
  fitbenchmarking/core/__init__.py
  fitbenchmarking/core/fitbenchmark_one_problem.py
  fitbenchmarking/core/fitting_benchmarking.py
  fitbenchmarking/core/results_output.py
  fitbenchmarking/results_processing/__init__.py
  fitbenchmarking/results_processing/plots.py
  fitbenchmarking/results_processing/visual_pages.py
Labels: Maintenance, Refactor

#403 Issue #395: Rewrite parser to improve bracket handling
  fitbenchmarking/parsing/fitbenchmark_parser.py
Labels: Data Modelling Software, Maintenance

#402 Local minimizer table
  examples/all_softwares.ini
  examples/options_template.ini
  fitbenchmarking/HTML_templates/problem_index_page.html
  fitbenchmarking/core/results_output.py
  fitbenchmarking/utils/default_options.ini
  fitbenchmarking/utils/fitbm_result.py
Labels: Enhancement

#407 Remove extra third party output
  fitbenchmarking/core/fitbenchmark_one_problem.py
  fitbenchmarking/core/fitting_benchmarking.py
  fitbenchmarking/utils/output_grabber.py
  fitbenchmarking/utils/tests/test_output_grabber.py
Labels: Enhancement

#425 Adds options test for getboolean and getint
  fitbenchmarking/utils/options.py
  fitbenchmarking/utils/tests/test_options.py
Labels: In progress

#424 Issue #410: Complete first draft of file structure docs
  docs/source/contributors/structure.rst
Labels: Documentation

#415 Adding fitbenchmarking.com css style
  .gitignore
  fitbenchmarking/HTML_templates/custom_style.css
  fitbenchmarking/HTML_templates/index_page.html
  fitbenchmarking/HTML_templates/main_style.css
  fitbenchmarking/HTML_templates/problem_index_page.html
  fitbenchmarking/HTML_templates/style_sheet.css
  fitbenchmarking/HTML_templates/style_sheet.py
  fitbenchmarking/HTML_templates/support_page_template.html
  fitbenchmarking/HTML_templates/table_style.css
  fitbenchmarking/HTML_templates/table_template.html
  fitbenchmarking/cli/main.py
  fitbenchmarking/core/results_output.py
  fitbenchmarking/fonts/FiraSans/eot/FiraSans-Bold.eot
  fitbenchmarking/fonts/FiraSans/eot/FiraSans-BoldItalic.eot
  fitbenchmarking/fonts/FiraSans/eot/FiraSans-Italic.eot
  fitbenchmarking/fonts/FiraSans/eot/FiraSans-Light.eot
  fitbenchmarking/fonts/FiraSans/eot/FiraSans-LightItalic.eot
  fitbenchmarking/fonts/FiraSans/eot/FiraSans-Medium.eot
  fitbenchmarking/fonts/FiraSans/eot/FiraSans-MediumItalic.eot
  fitbenchmarking/fonts/FiraSans/eot/FiraSans-Regular.eot
  fitbenchmarking/fonts/FiraSans/ttf/FiraSans-Bold.ttf
  fitbenchmarking/fonts/FiraSans/ttf/FiraSans-BoldItalic.ttf
  fitbenchmarking/fonts/FiraSans/ttf/FiraSans-Italic.ttf
  fitbenchmarking/fonts/FiraSans/ttf/FiraSans-Light.ttf
  fitbenchmarking/fonts/FiraSans/ttf/FiraSans-LightItalic.ttf
  fitbenchmarking/fonts/FiraSans/ttf/FiraSans-Medium.ttf
  fitbenchmarking/fonts/FiraSans/ttf/FiraSans-MediumItalic.ttf
  fitbenchmarking/fonts/FiraSans/ttf/FiraSans-Regular.ttf
  fitbenchmarking/fonts/FiraSans/woff/FiraSans-Bold.woff
  fitbenchmarking/fonts/FiraSans/woff/FiraSans-BoldItalic.woff
  fitbenchmarking/fonts/FiraSans/woff/FiraSans-Italic.woff
  fitbenchmarking/fonts/FiraSans/woff/FiraSans-Light.woff
  fitbenchmarking/fonts/FiraSans/woff/FiraSans-LightItalic.woff
  fitbenchmarking/fonts/FiraSans/woff/FiraSans-Medium.woff
  fitbenchmarking/fonts/FiraSans/woff/FiraSans-MediumItalic.woff
  fitbenchmarking/fonts/FiraSans/woff/FiraSans-Regular.woff
  fitbenchmarking/fonts/FiraSans/woff2/FiraSans-Bold.woff2
  fitbenchmarking/fonts/FiraSans/woff2/FiraSans-BoldItalic.woff2
  fitbenchmarking/fonts/FiraSans/woff2/FiraSans-Italic.woff2
  fitbenchmarking/fonts/FiraSans/woff2/FiraSans-Light.woff2
  fitbenchmarking/fonts/FiraSans/woff2/FiraSans-LightItalic.woff2
  fitbenchmarking/fonts/FiraSans/woff2/FiraSans-Medium.woff2
  fitbenchmarking/fonts/FiraSans/woff2/FiraSans-MediumItalic.woff2
  fitbenchmarking/fonts/FiraSans/woff2/FiraSans-Regular.woff2
  fitbenchmarking/fonts/FontAwesome/fontawesome-webfont.eot
  fitbenchmarking/fonts/FontAwesome/fontawesome-webfont.svg
  fitbenchmarking/fonts/FontAwesome/fontawesome-webfont.ttf
  fitbenchmarking/fonts/FontAwesome/fontawesome-webfont.woff
  fitbenchmarking/fonts/FontAwesome/fontawesome-webfont.woff2
  fitbenchmarking/results_processing/support_page.py
  fitbenchmarking/results_processing/tables.py
Labels: In progress
