Repository fitbenchmarking/fitbenchmarking, pull requests merged in 2021-11, with the labels that each got.

#962 Run Unit tests in one call
  ci/unit_tests.sh
  ci/unit_tests_default.sh
Labels: Testing

#951 Refactor Cost Functions and Jacobians
  docs/source/extending/controllers.rst
  docs/source/extending/cost_function.rst
  docs/source/extending/hessian_extend.rst
  docs/source/extending/jacobian_extend.rst
  docs/source/users/cost_func.rst
  fitbenchmarking/controllers/base_controller.py
  fitbenchmarking/controllers/gsl_controller.py
  fitbenchmarking/controllers/levmar_controller.py
  fitbenchmarking/controllers/mantid_controller.py
  fitbenchmarking/controllers/matlab_controller.py
  fitbenchmarking/controllers/matlab_mixin.py
  fitbenchmarking/controllers/matlab_opt_controller.py
  fitbenchmarking/controllers/matlab_stats_controller.py
  fitbenchmarking/controllers/ralfit_controller.py
  fitbenchmarking/controllers/scipy_controller.py
  fitbenchmarking/controllers/scipy_go_controller.py
  fitbenchmarking/controllers/scipy_ls_controller.py
  fitbenchmarking/controllers/tests/test_controllers.py
  fitbenchmarking/core/fitting_benchmarking.py
  fitbenchmarking/core/tests/test_fitting_benchmarking_hessians.py
  fitbenchmarking/core/tests/test_results_output.py
  fitbenchmarking/cost_func/base_cost_func.py
  fitbenchmarking/cost_func/hellinger_nlls_cost_func.py
  fitbenchmarking/cost_func/nlls_base_cost_func.py
  fitbenchmarking/cost_func/nlls_cost_func.py
  fitbenchmarking/cost_func/poisson_cost_func.py
  fitbenchmarking/cost_func/tests/test_cost_func.py
  fitbenchmarking/cost_func/weighted_nlls_cost_func.py
  fitbenchmarking/hessian/analytic_hessian.py
  fitbenchmarking/hessian/base_hessian.py
  fitbenchmarking/hessian/tests/test_hessian.py
  fitbenchmarking/jacobian/analytic_jacobian.py
  fitbenchmarking/jacobian/base_jacobian.py
  fitbenchmarking/jacobian/default_jacobian.py
  fitbenchmarking/jacobian/numdifftools_jacobian.py
  fitbenchmarking/jacobian/scipy_jacobian.py
  fitbenchmarking/jacobian/tests/test_jacobian.py
  fitbenchmarking/parsing/fitting_problem.py
  fitbenchmarking/results_processing/local_min_table.py
  fitbenchmarking/results_processing/tests/test_tables.py
  fitbenchmarking/systests/linux_expected_results/all_parsers.txt
  fitbenchmarking/systests/linux_expected_results/default_parsers.txt
  fitbenchmarking/utils/tests/test_fitbm_result.py
Labels: Bug, Maintenance

#966 Specify minimizers in regression tests
  fitbenchmarking/systests/linux_expected_results/all_parsers.txt
  fitbenchmarking/systests/linux_expected_results/default_parsers.txt
  fitbenchmarking/systests/linux_expected_results/multifit.txt
  fitbenchmarking/systests/test_regression.py
Labels: Testing

#967 Remove minus from NIST and Cutest parser
  fitbenchmarking/jacobian/analytic_jacobian.py
  fitbenchmarking/jacobian/tests/test_jacobian.py
  fitbenchmarking/parsing/cutest_parser.py
  fitbenchmarking/parsing/nist_data_functions.py
  fitbenchmarking/parsing/tests/cutest/jacobian_evaluations.json
  fitbenchmarking/parsing/tests/nist/jacobian_evaluations.json
  fitbenchmarking/results_processing/tests/test_base_table.py
Labels: Bug, Maintenance

#963 Pylint - Fail on refactor and convention warnings
  .pylintrc
  ci/linting_tests.sh
  fitbenchmarking/cli/main.py
  fitbenchmarking/cli/tests/test_main.py
  fitbenchmarking/controllers/scipy_go_controller.py
  fitbenchmarking/controllers/tests/test_controllers.py
  fitbenchmarking/core/fitting_benchmarking.py
  fitbenchmarking/core/tests/test_results_output.py
  fitbenchmarking/jacobian/analytic_jacobian.py
  fitbenchmarking/jacobian/default_jacobian.py
  fitbenchmarking/jacobian/scipy_jacobian.py
  fitbenchmarking/parsing/fitbenchmark_parser.py
  fitbenchmarking/parsing/fitting_problem.py
  fitbenchmarking/parsing/ivp_parser.py
  fitbenchmarking/parsing/mantid_parser.py
  fitbenchmarking/parsing/nist_parser.py
  fitbenchmarking/parsing/sasview_parser.py
  fitbenchmarking/results_processing/base_table.py
  fitbenchmarking/results_processing/local_min_table.py
  fitbenchmarking/results_processing/performance_profiler.py
  fitbenchmarking/results_processing/tables.py
  fitbenchmarking/results_processing/tests/test_base_table.py
  fitbenchmarking/results_processing/tests/test_problem_summary_page.py
  fitbenchmarking/systests/test_regression.py
  fitbenchmarking/utils/tests/test_misc.py
  fitbenchmarking/utils/tests/test_options_generic.py
  fitbenchmarking/utils/tests/test_options_minimizers.py
Labels: Testing

#968 Add `minuit` and `dfo` to the regression tests
  fitbenchmarking/mock_problems/all_parsers_set/1D_sphere_neutron_def0.txt
  fitbenchmarking/mock_problems/all_parsers_set/BENNETT5.SIF
  fitbenchmarking/mock_problems/all_parsers_set/DANWOOD.SIF
  fitbenchmarking/mock_problems/all_parsers_set/DanWood.dat
  fitbenchmarking/mock_problems/all_parsers_set/Muon_EMU_73673.txt
  fitbenchmarking/mock_problems/all_parsers_set/cubic-fba.txt
  fitbenchmarking/mock_problems/all_parsers_set/cubic.dat
  fitbenchmarking/mock_problems/all_parsers_set/data_files/1D_sphere_50_nosmearing_neutron_synth.txt
  fitbenchmarking/mock_problems/all_parsers_set/data_files/DanWood.hes
  fitbenchmarking/mock_problems/all_parsers_set/data_files/DanWood.jac
  fitbenchmarking/mock_problems/all_parsers_set/data_files/EMU_116891_long.txt
  fitbenchmarking/mock_problems/all_parsers_set/data_files/cubic.jac
  fitbenchmarking/mock_problems/all_parsers_set/data_files/cubic.txt
  fitbenchmarking/mock_problems/all_parsers_set/data_files/cyl_400_20.txt
  fitbenchmarking/mock_problems/all_parsers_set/data_files/trig_noisy.txt
  fitbenchmarking/mock_problems/all_parsers_set/prob_def_1.txt
  fitbenchmarking/mock_problems/all_parsers_set/trig_noisy-fba.txt
  fitbenchmarking/systests/linux_expected_results/all_parsers.txt
  fitbenchmarking/systests/test_regression.py
Labels: Testing

#978 Minor updates to documentation
  fitbenchmarking/utils/options.py
Labels: Documentation

#977 Fix Mantid MultiFit results when using more than one Jacobian/Hessian
  fitbenchmarking/core/fitting_benchmarking.py
  fitbenchmarking/core/tests/test_fitting_benchmarking_hessians.py
  fitbenchmarking/core/tests/test_fitting_benchmarking_jacobians.py
  fitbenchmarking/core/tests/test_fitting_benchmarking_minimizers.py
  fitbenchmarking/systests/linux_expected_results/multifit.txt
  fitbenchmarking/systests/test_regression.py
Labels: Bug

#981 Update comparison tables in the documentation
  docs/images/example_table.png
Labels: Documentation

#984 Fix default jacobians for `gsl`, `mantid`, `scipy - Newton CG` and `RALFit`
  fitbenchmarking/controllers/mantid_controller.py
  fitbenchmarking/controllers/scipy_controller.py
  fitbenchmarking/controllers/tests/test_controllers.py
  fitbenchmarking/jacobian/default_jacobian.py
  fitbenchmarking/jacobian/tests/test_jacobian.py
  fitbenchmarking/results_processing/local_min_table.py
Labels: Bug
