Repository fitbenchmarking/fitbenchmarking, pull requests merged in 2024-11, with the labels that each got.

#1355 Fixed the problem name bug
  fitbenchmarking/parsing/fitbenchmark_parser.py
  fitbenchmarking/parsing/tests/test_parsers.py
Labels: ignore-for-release

#1307 Added number of iterations/function evaluations to fitting report
  docs/source/users/install_instructions/fitbenchmarking.rst
  fitbenchmarking/controllers/base_controller.py
  fitbenchmarking/controllers/ceres_controller.py
  fitbenchmarking/controllers/dfo_controller.py
  fitbenchmarking/controllers/gradient_free_controller.py
  fitbenchmarking/controllers/gsl_controller.py
  fitbenchmarking/controllers/levmar_controller.py
  fitbenchmarking/controllers/lmfit_controller.py
  fitbenchmarking/controllers/matlab_controller.py
  fitbenchmarking/controllers/matlab_curve_controller.py
  fitbenchmarking/controllers/matlab_opt_controller.py
  fitbenchmarking/controllers/minuit_controller.py
  fitbenchmarking/controllers/ralfit_controller.py
  fitbenchmarking/controllers/scipy_controller.py
  fitbenchmarking/controllers/scipy_go_controller.py
  fitbenchmarking/controllers/scipy_leastsq_controller.py
  fitbenchmarking/controllers/scipy_ls_controller.py
  fitbenchmarking/controllers/tests/test_controllers.py
  fitbenchmarking/core/tests/test_fitting_benchmarking.py
  fitbenchmarking/results_processing/fitting_report.py
  fitbenchmarking/templates/fitting_report_template.html
  fitbenchmarking/test_files/checkpoint.json
  fitbenchmarking/test_files/regression_checkpoint.json
  fitbenchmarking/utils/checkpoint.py
  fitbenchmarking/utils/fitbm_result.py
  fitbenchmarking/utils/tests/test_checkpoint.py
Labels: pr-feature

#1358 Fixed the bad error msg
  fitbenchmarking/utils/options.py
  fitbenchmarking/utils/tests/test_options_minimizers.py
Labels: ignore-for-release

#1356 Fixed the perfect fit divide by zero error
  fitbenchmarking/results_processing/base_table.py
  fitbenchmarking/templates/table_descriptions.rst
  fitbenchmarking/utils/fitbm_result.py
  fitbenchmarking/utils/tests/test_fitbm_result.py
Labels: ignore-for-release

#1363 Added the C4 ruleset to ruff
  .pre-commit-config.yaml
  fitbenchmarking/cli/tests/test_checkpoint_handler.py
  fitbenchmarking/controllers/lmfit_controller.py
  fitbenchmarking/results_processing/base_table.py
  fitbenchmarking/results_processing/tests/test_base_table.py
  fitbenchmarking/results_processing/tests/test_fitting_report.py
  pyproject.toml
Labels: ignore-for-release

#1353 Fixed the Multifit problem bug
  fitbenchmarking/parsing/fitting_problem.py
  fitbenchmarking/parsing/tests/test_fitting_problem.py
Labels: ignore-for-release

#1369 Added 6 more ruff rulesets
  docs/source/conf.py
  fitbenchmarking/controllers/mantid_controller.py
  fitbenchmarking/core/results_output.py
  fitbenchmarking/hessian/best_available_hessian.py
  fitbenchmarking/jacobian/best_available_jacobian.py
  fitbenchmarking/parsing/parser_factory.py
  fitbenchmarking/results_processing/local_min_table.py
  fitbenchmarking/systests/test_regression.py
  fitbenchmarking/utils/fitbm_result.py
  pyproject.toml
Labels: ignore-for-release

#1354 Added integration workflow
  .github/workflows/integration.yml
  .github/workflows/main.yml
Labels: ignore-for-release

#1365 Added python and numpy version tags to checkpoint.json
  .pre-commit-config.yaml
  fitbenchmarking/cli/checkpoint_handler.py
  fitbenchmarking/cli/main.py
  fitbenchmarking/core/results_output.py
  fitbenchmarking/core/tests/test_results_output.py
  fitbenchmarking/hessian/best_available_hessian.py
  fitbenchmarking/jacobian/best_available_jacobian.py
  fitbenchmarking/results_processing/tables.py
  fitbenchmarking/results_processing/tests/test_base_table.py
  fitbenchmarking/results_processing/tests/test_fitting_report.py
  fitbenchmarking/results_processing/tests/test_performance_profiler.py
  fitbenchmarking/results_processing/tests/test_plots.py
  fitbenchmarking/results_processing/tests/test_problem_summary_page.py
  fitbenchmarking/results_processing/tests/test_tables.py
  fitbenchmarking/templates/css/custom_style.css
  fitbenchmarking/templates/fitting_report_template.html
  fitbenchmarking/templates/images/fitbenchmarking_logo.png
  fitbenchmarking/templates/index_page.html
  fitbenchmarking/templates/problem_index_page.html
  fitbenchmarking/templates/problem_summary_page_template.html
  fitbenchmarking/templates/table_descriptions.rst
  fitbenchmarking/templates/table_template.html
  fitbenchmarking/test_files/checkpoint.json
  fitbenchmarking/utils/checkpoint.py
  fitbenchmarking/utils/tests/test_checkpoint.py
Labels: pr-fix

#1364 Updated default system tests so that they run python 3.12
  .github/workflows/main.yml
Labels: ignore-for-release

#1334 Updated minimum supported version of python to 3.9.x
  .github/workflows/build_container.yml
  .github/workflows/install.yml
  .github/workflows/main.yml
  docs/source/contributors/guidelines.rst
  docs/source/users/install_instructions/fitbenchmarking.rst
  fitbenchmarking/cli/checkpoint_handler.py
  fitbenchmarking/controllers/theseus_controller.py
  fitbenchmarking/core/results_output.py
  fitbenchmarking/parsing/fitbenchmark_parser.py
  fitbenchmarking/parsing/mantiddev_parser.py
  fitbenchmarking/results_processing/performance_profiler.py
  fitbenchmarking/utils/checkpoint.py
  fitbenchmarking/utils/fitbm_result.py
  fitbenchmarking/utils/tests/test_fitbm_result.py
  pyproject.toml
Labels: pr-fix

#1352 Added a more descriptive error msg when default problem set is missing
  fitbenchmarking/cli/main.py
  fitbenchmarking/cli/tests/test_main.py
  fitbenchmarking/utils/exceptions.py
  fitbenchmarking/utils/tests/test_write_files.py
  fitbenchmarking/utils/write_files.py
Labels: ignore-for-release

#1375 Upload coveralls even after failed tests
  .github/workflows/main.yml
Labels: ignore-for-release

#1381 Added images to the problem index page
  fitbenchmarking/templates/css/custom_style.css
  fitbenchmarking/templates/images/accuracy.png
  fitbenchmarking/templates/images/compare.png
  fitbenchmarking/templates/images/energy.png
  fitbenchmarking/templates/images/local_min.png
  fitbenchmarking/templates/images/runtime.png
  fitbenchmarking/templates/problem_index_page.html
Labels: ignore-for-release

#1380 Added parameters to the problem summary page
  fitbenchmarking/results_processing/base_table.py
  fitbenchmarking/results_processing/problem_summary_page.py
  fitbenchmarking/templates/css/custom_style.css
  fitbenchmarking/templates/fitting_report_template.html
  fitbenchmarking/templates/problem_summary_page_template.html
  fitbenchmarking/templates/table_template.html
Labels: ignore-for-release

#1377 Measure energy usage instead of emissions
  docs/source/users/options/output_option.rst
  docs/source/users/output/emissions.rst
  docs/source/users/output/energy_usage.rst
  docs/source/users/output/index.rst
  fitbenchmarking/cli/checkpoint_handler.py
  fitbenchmarking/cli/tests/test_checkpoint_handler.py
  fitbenchmarking/cli/tests/test_files/A.json
  fitbenchmarking/cli/tests/test_files/AB.json
  fitbenchmarking/cli/tests/test_files/B.json
  fitbenchmarking/cli/tests/test_files/C.json
  fitbenchmarking/cli/tests/test_files/D.json
  fitbenchmarking/core/fitting_benchmarking.py
  fitbenchmarking/core/results_output.py
  fitbenchmarking/core/tests/test_fitting_benchmarking.py
  fitbenchmarking/results_processing/energy_usage_table.py
  fitbenchmarking/results_processing/fitting_report.py
  fitbenchmarking/results_processing/performance_profiler.py
  fitbenchmarking/results_processing/tables.py
  fitbenchmarking/results_processing/tests/expected_results/energy_usage.csv
  fitbenchmarking/results_processing/tests/expected_results/energy_usage.html
  fitbenchmarking/results_processing/tests/test_base_table.py
  fitbenchmarking/results_processing/tests/test_performance_profiler.py
  fitbenchmarking/results_processing/tests/test_tables.py
  fitbenchmarking/templates/fitting_report_template.html
  fitbenchmarking/templates/table_descriptions.rst
  fitbenchmarking/test_files/checkpoint.json
  fitbenchmarking/test_files/regression_checkpoint.json
  fitbenchmarking/utils/checkpoint.py
  fitbenchmarking/utils/fitbm_result.py
  fitbenchmarking/utils/options.py
  fitbenchmarking/utils/tests/test_fitbm_result.py
  fitbenchmarking/utils/tests/test_options_output.py
Labels: pr-feature

#1367 Updated regression tests and documentation on compatibility
  docs/source/users/notes.rst
  fitbenchmarking/systests/linux_expected_results/all_parsers.csv
Labels: ignore-for-release

#1385 Fixed the disappearance of the error table header
  fitbenchmarking/templates/js/table.js
Labels: ignore-for-release

#1387 Removed suggestions to install Intel Power Gadget
  fitbenchmarking/results_processing/energy_usage_table.py
  fitbenchmarking/templates/table_descriptions.rst
Labels: ignore-for-release

#1376 Added synthetic Gaussian data to test mantid fitting
  examples/benchmark_problems/synthetic_data/gaussian/A0_1.txt
  examples/benchmark_problems/synthetic_data/gaussian/A0_2.txt
  examples/benchmark_problems/synthetic_data/gaussian/A0_3.txt
  examples/benchmark_problems/synthetic_data/gaussian/A0_4.txt
  examples/benchmark_problems/synthetic_data/gaussian/META.txt
  examples/benchmark_problems/synthetic_data/gaussian/data_files/low_stats_gaussian.dat
  examples/benchmark_problems/synthetic_data/gaussian/height_1.txt
  examples/benchmark_problems/synthetic_data/gaussian/height_2.txt
  examples/benchmark_problems/synthetic_data/gaussian/height_3.txt
  examples/benchmark_problems/synthetic_data/gaussian/height_4.txt
  examples/benchmark_problems/synthetic_data/gaussian/peak_centre_1.txt
  examples/benchmark_problems/synthetic_data/gaussian/peak_centre_2.txt
  examples/benchmark_problems/synthetic_data/gaussian/peak_centre_3.txt
  examples/benchmark_problems/synthetic_data/gaussian/peak_centre_4.txt
  examples/benchmark_problems/synthetic_data/gaussian/sigma_1.txt
  examples/benchmark_problems/synthetic_data/gaussian/sigma_2.txt
  examples/benchmark_problems/synthetic_data/gaussian/sigma_3.txt
  examples/benchmark_problems/synthetic_data/gaussian/sigma_4.txt
Labels: pr-feature

#1389 Made code compatible with ruff 0.8.0
  .pre-commit-config.yaml
  fitbenchmarking/parsing/tests/test_parsers.py
Labels: ignore-for-release

#1392 Fixed the wrong table descriptions
  fitbenchmarking/core/results_output.py
  fitbenchmarking/results_processing/base_table.py
  fitbenchmarking/templates/problem_index_page.html
  fitbenchmarking/templates/table_descriptions.rst
Labels: ignore-for-release

#1394 Updated the README.md to remove mention of support email
  README.md
Labels: ignore-for-release

#1393 Updated the simple table to remove white space
  fitbenchmarking/templates/css/custom_style.css
  fitbenchmarking/templates/fitting_report_template.html
  fitbenchmarking/templates/problem_summary_page_template.html
Labels: ignore-for-release

#1372 Added support for python 3.13.x
  .github/workflows/integration.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
  fitbenchmarking/core/tests/test_fitting_benchmarking.py
  fitbenchmarking/parsing/nist_data_functions.py
Labels: pr-feature

#1370 Added concurrency groups to workflows
  .github/workflows/linting.yml
  .github/workflows/main.yml
Labels: ignore-for-release

#1396 Fixed authors typo in pyproject.toml
  pyproject.toml
Labels: ignore-for-release

#1395 Updated install.yml to test install on python 3.13.x
  .github/workflows/install.yml
Labels: ignore-for-release

#1397 Updated Zenodo link in README.md
  README.md
Labels: ignore-for-release

#1271 Fixed corruption in checkpoint file after an exception
  fitbenchmarking/cli/main.py
  fitbenchmarking/cli/tests/test_main.py
Labels: pr-fix
