Repository fitbenchmarking/fitbenchmarking, pull requests merged in 2024-05, with the labels that each got.

#1280 Updated build commands in release workflow
  .github/workflows/release.yml
Labels: Bug, ignore-for-release

#1251 Added `best_available` jacobian option to allow for sets with only some analytic
  docs/source/users/options/fitting_option.rst
  docs/source/users/options/hessian_option.rst
  docs/source/users/options/jacobian_option.rst
  fitbenchmarking/core/results_output.py
  fitbenchmarking/core/tests/test_results_fallback.py
  fitbenchmarking/hessian/best_available_hessian.py
  fitbenchmarking/hessian/hessian_factory.py
  fitbenchmarking/hessian/tests/test_hessian.py
  fitbenchmarking/jacobian/best_available_jacobian.py
  fitbenchmarking/jacobian/jacobian_factory.py
  fitbenchmarking/jacobian/tests/test_jacobian.py
  fitbenchmarking/systests/linux_expected_results/all_parsers.csv
  fitbenchmarking/systests/linux_expected_results/default_parsers_set.csv
  fitbenchmarking/systests/linux_expected_results/matlab.csv
  fitbenchmarking/systests/linux_expected_results/multifit.csv
  fitbenchmarking/systests/test_regression.py
  fitbenchmarking/test_files/fallbackcase1.json
  fitbenchmarking/test_files/fallbackcase2.json
  fitbenchmarking/test_files/fallbackcase3.json
  fitbenchmarking/test_files/fallbackcase4.json
  fitbenchmarking/test_files/fallbackcase5.json
  fitbenchmarking/test_files/fallbackcase6.json
  fitbenchmarking/test_files/fallbackcase7.json
  fitbenchmarking/test_files/regression_checkpoint.json
  fitbenchmarking/utils/options.py
  fitbenchmarking/utils/tests/test_options_fitting.py
  fitbenchmarking/utils/tests/test_options_hessian.py
  fitbenchmarking/utils/tests/test_options_jacobian.py
Labels: pr-feature

#1285 Improved performance of codecarbon calls on Windows machines
  fitbenchmarking/core/fitting_benchmarking.py
  fitbenchmarking/core/tests/test_fitting_benchmarking.py
Labels: pr-fix

#1286 Removed checkpoint file
  checkpoint.json
Labels: ignore-for-release

#1279 Added errorbars to the plots in the fitting report
  fitbenchmarking/results_processing/plots.py
  fitbenchmarking/results_processing/tests/test_plots.py
Labels: ignore-for-release

#1287 Fixed emissions display when not measured
  examples/options_template.ini
  fitbenchmarking/results_processing/fitting_report.py
  fitbenchmarking/templates/fitting_report_template.html
Labels: pr-fix

#1263 Added flags for sparsity
  fitbenchmarking/controllers/base_controller.py
  fitbenchmarking/controllers/scipy_ls_controller.py
  fitbenchmarking/core/fitting_benchmarking.py
  fitbenchmarking/core/tests/test_fitting_benchmarking.py
Labels: pr-feature
