Repository fitbenchmarking/fitbenchmarking, pull requests merged in 2024-12, with the labels that each got.

#1398 Removed the Linting GitHub actions workflow
  .github/workflows/linting.yml
  .pre-commit-config.yaml
Labels: ignore-for-release

#1401 Added check for `nfev` and `nit` attributes in scipy controller
  fitbenchmarking/controllers/scipy_controller.py
Labels: pr-fix

#1403 Updated the location of external data files
  docs/source/users/BenchmarkProblems.rst
Labels: Bug, Documentation

#1388 Fixed the warnings on docs build
  docs/source/conf.py
  docs/source/contributors/guidelines.rst
  docs/source/contributors/install_instructions.rst
  docs/source/contributors/workflow.rst
  docs/source/extending/adding_data.rst
  docs/source/extending/fitting_results.rst
  docs/source/extending/index.rst
  docs/source/users/BenchmarkProblems.rst
  docs/source/users/algorithms/deriv_free.rst
  docs/source/users/algorithms/line_search.rst
  docs/source/users/algorithms/trust_region.rst
  docs/source/users/install_instructions/externals.rst
  docs/source/users/options/minimizer_option.rst
  docs/source/users/output/fitting_report.rst
  docs/source/users/problem_definition_files/horace.rst
  docs/source/users/running.rst
  docs/source/users/tutorials.rst
  fitbenchmarking/cli/checkpoint_handler.py
  fitbenchmarking/cli/main.py
  fitbenchmarking/controllers/base_controller.py
  fitbenchmarking/controllers/ralfit_controller.py
  fitbenchmarking/core/results_output.py
  fitbenchmarking/cost_func/base_cost_func.py
  fitbenchmarking/parsing/fitting_problem.py
  fitbenchmarking/results_processing/tables.py
  fitbenchmarking/utils/options.py
Labels: ignore-for-release
