Repository fitbenchmarking/fitbenchmarking, pull requests merged in 2024-01, with the labels that each got.

#1216 Fixed bug where the emissions table showed a runtime performance profile
  fitbenchmarking/results_processing/acc_table.py
  fitbenchmarking/results_processing/base_table.py
  fitbenchmarking/results_processing/compare_table.py
  fitbenchmarking/results_processing/emissions_table.py
  fitbenchmarking/results_processing/local_min_table.py
  fitbenchmarking/results_processing/performance_profiler.py
  fitbenchmarking/results_processing/runtime_table.py
  fitbenchmarking/results_processing/tables.py
  fitbenchmarking/results_processing/tests/test_base_table.py
  fitbenchmarking/results_processing/tests/test_performance_profiler.py
  fitbenchmarking/results_processing/tests/test_tables.py
Labels: pr-patch-change

#1215 Fixed issue with back page button not working after introducing Dash.
  fitbenchmarking/templates/js/table.js
  fitbenchmarking/templates/table_template.html
Labels: pr-fix

#1224 Bumped sphinx version for docs
  docs/requirements.txt
Labels: pr-fix

#1204 Added support for HOGBEN
  .github/workflows/main.yml
  docs/source/users/BenchmarkProblems.rst
  docs/source/users/install_instructions/fitbenchmarking.rst
  docs/source/users/problem_definition_files/hogben.rst
  docs/source/users/problem_definition_files/index.rst
  examples/benchmark_problems/HOGBEN_samples/Models/many_param_sample_model.pkl
  examples/benchmark_problems/HOGBEN_samples/Models/similar_sld1_sample_model.pkl
  examples/benchmark_problems/HOGBEN_samples/Models/similar_sld2_sample_model.pkl
  examples/benchmark_problems/HOGBEN_samples/Models/similar_sld_sample_1_model.pkl
  examples/benchmark_problems/HOGBEN_samples/Models/similar_sld_sample_2_model.pkl
  examples/benchmark_problems/HOGBEN_samples/Models/simple_sample_model.pkl
  examples/benchmark_problems/HOGBEN_samples/Models/thin_layer_sample_1_model.pkl
  examples/benchmark_problems/HOGBEN_samples/Models/thin_layer_sample_2_model.pkl
  examples/benchmark_problems/HOGBEN_samples/data/many_param_sample.txt
  examples/benchmark_problems/HOGBEN_samples/data/similar_sld1_sample.txt
  examples/benchmark_problems/HOGBEN_samples/data/similar_sld2_sample.txt
  examples/benchmark_problems/HOGBEN_samples/data/similar_sld_sample_1.txt
  examples/benchmark_problems/HOGBEN_samples/data/similar_sld_sample_2.txt
  examples/benchmark_problems/HOGBEN_samples/data/simple_sample.txt
  examples/benchmark_problems/HOGBEN_samples/data/thin_layer_sample_1.txt
  examples/benchmark_problems/HOGBEN_samples/data/thin_layer_sample_2.txt
  examples/benchmark_problems/HOGBEN_samples/many_param_sample.txt
  examples/benchmark_problems/HOGBEN_samples/similar_sld_sample_1.txt
  examples/benchmark_problems/HOGBEN_samples/similar_sld_sample_2.txt
  examples/benchmark_problems/HOGBEN_samples/simple_sample.txt
  examples/benchmark_problems/HOGBEN_samples/thin_layer_sample_1.txt
  examples/benchmark_problems/HOGBEN_samples/thin_layer_sample_2.txt
  examples/benchmark_problems/scripts/generate_simulated_hogben.py
  fitbenchmarking/parsing/hogben_parser.py
  fitbenchmarking/parsing/tests/hogben/Models/simple_sample_model.pkl
  fitbenchmarking/parsing/tests/hogben/basic.txt
  fitbenchmarking/parsing/tests/hogben/data/simple_sample.txt
  fitbenchmarking/parsing/tests/hogben/function_evaluations.json
  fitbenchmarking/parsing/tests/hogben/simple_sample.txt
  fitbenchmarking/parsing/tests/hogben/start_end_x.txt
  fitbenchmarking/parsing/tests/test_parsers.py
  fitbenchmarking/systests/linux_expected_results/all_parsers.csv
  fitbenchmarking/test_files/all_parsers_set/Models/simple_sample_model.pkl
  fitbenchmarking/test_files/all_parsers_set/data_files/simple_sample.txt
  fitbenchmarking/test_files/all_parsers_set/simple_sample.txt
  setup.py
Labels: pr-feature
