Repository fitbenchmarking/fitbenchmarking, pull requests merged in 2025-03, with the labels that each got.

#1450 Updated fitting result table to show initial and fitted parameters side by side for a better ux
  fitbenchmarking/templates/css/custom_style.css
  fitbenchmarking/templates/fitting_report_template.html
Labels: ignore-for-release

#1419 Refactored the FitbenchmarkingParser class and added more unit tests
  examples/benchmark_problems/Data_Assimilation/functions/lorentz.py
  examples/benchmark_problems/Data_Assimilation/functions/simplified_anac.py
  fitbenchmarking/parsing/fitbenchmark_parser.py
  fitbenchmarking/parsing/ivp_parser.py
  fitbenchmarking/parsing/mantiddev_parser.py
  fitbenchmarking/parsing/tests/ivp/functions/simplified_anac.py
  fitbenchmarking/parsing/tests/test_fitbenchmark_parser.py
  fitbenchmarking/parsing/tests/test_parsers.py
Labels: pr-breaking

#1411 Added check to compare jacobian computed by fitbenchmarking with that obtained through finite differences
  docs/source/users/running.rst
  fitbenchmarking/cli/main.py
  fitbenchmarking/core/fitting_benchmarking.py
  fitbenchmarking/core/tests/test_fitting_benchmarking.py
  fitbenchmarking/utils/options.py
Labels: pr-feature

#1457 Added SLF ruleset to check private member access through ruff
  fitbenchmarking/controllers/bumps_controller.py
  pyproject.toml
Labels: ignore-for-release

#1455 Refactored the MantidParser and MantidDevParser class and added more unit tests
  fitbenchmarking/parsing/horace_parser.py
  fitbenchmarking/parsing/mantiddev_parser.py
  fitbenchmarking/parsing/tests/mantid/basic.txt
  fitbenchmarking/parsing/tests/mantid/data_files/mantid_basic.dat
  fitbenchmarking/parsing/tests/mantid/data_files/mantid_start_end_x.dat
  fitbenchmarking/parsing/tests/mantid/data_files/multifit1.txt
  fitbenchmarking/parsing/tests/mantid/data_files/multifit2.txt
  fitbenchmarking/parsing/tests/mantid/function_evaluations.json
  fitbenchmarking/parsing/tests/mantid/jacobian_evaluations.json
  fitbenchmarking/parsing/tests/mantid/jacobian_functions/simple_jac.py
  fitbenchmarking/parsing/tests/mantid/multifit.txt
  fitbenchmarking/parsing/tests/mantid/sparse_jacobian_evaluations.json
  fitbenchmarking/parsing/tests/mantid/start_end_x.txt
  fitbenchmarking/parsing/tests/test_fitbenchmark_parser.py
  fitbenchmarking/parsing/tests/test_mantid_parsers.py
  fitbenchmarking/parsing/tests/test_parsers.py
  pyproject.toml
Labels: pr-breaking

#1462 Updated the fitting report template to consolidate the graphs and tables
  docs/source/users/running.rst
  fitbenchmarking/results_processing/fitting_report.py
  fitbenchmarking/results_processing/plots.py
  fitbenchmarking/results_processing/tests/test_fitting_report.py
  fitbenchmarking/templates/fitting_report_template.html
Labels: ignore-for-release

#1465 Fixed the failing main, integration and install tests
  .github/workflows/install.yml
  .github/workflows/integration.yml
  .github/workflows/main.yml
Labels: ignore-for-release

#1467 Revert the updates to the main, integration and install tests
  .github/workflows/install.yml
  .github/workflows/integration.yml
  .github/workflows/main.yml
Labels: ignore-for-release

#1461 Added a dropdown radio button menu to select the runtime metric for the compare and runtime tables
  fitbenchmarking/controllers/tests/test_controllers.py
  fitbenchmarking/core/results_output.py
  fitbenchmarking/core/tests/test_results_output.py
  fitbenchmarking/results_processing/base_table.py
  fitbenchmarking/results_processing/compare_table.py
  fitbenchmarking/results_processing/performance_profiler.py
  fitbenchmarking/results_processing/runtime_table.py
  fitbenchmarking/results_processing/tables.py
  fitbenchmarking/results_processing/tests/expected_results/compare.html
  fitbenchmarking/results_processing/tests/expected_results/runtime.html
  fitbenchmarking/templates/js/table.js
  fitbenchmarking/templates/table_template.html
  fitbenchmarking/test_files/checkpoint.json
  fitbenchmarking/test_files/regression_checkpoint.json
  fitbenchmarking/utils/checkpoint.py
  fitbenchmarking/utils/fitbm_result.py
  fitbenchmarking/utils/tests/test_fitbm_result.py
Labels: pr-feature

#1459 Reduced chain length for Bayesian controller tests
  fitbenchmarking/controllers/base_controller.py
  fitbenchmarking/controllers/bumps_controller.py
  fitbenchmarking/controllers/lmfit_controller.py
  fitbenchmarking/controllers/mantid_controller.py
  fitbenchmarking/controllers/paramonte_controller.py
  fitbenchmarking/controllers/tests/test_controllers.py
Labels: ignore-for-release

#1471 Fixed the bug that did not update the runtime in the fitting report
  fitbenchmarking/results_processing/fitting_report.py
  fitbenchmarking/templates/fitting_report_template.html
  fitbenchmarking/templates/js/table.js
  fitbenchmarking/templates/table_template.html
Labels: ignore-for-release
